Added contributing.md and security.md files
datakaveri/iudx-aaa-server pull request #273
Opened 2023-01-27 05:20 UTC by MohammedAman23

2023-01-27 05:37 UTC, ThorodanBrom commented on CONTRIBUTING.md
> +The [READMEmd](https://github.com/datakaveri/iudx-aaa-server/blob/main/README.md) file explains how to install the program locally (highly recommended if you're going to make code changes). It also p
Put dot here

2023-01-27 05:37 UTC, ThorodanBrom commented on CONTRIBUTING.md
> +Specific changes are proposed using those mechanisms.
Update URLs here

2023-01-27 05:39 UTC, ThorodanBrom commented on CONTRIBUTING.md
> +but we've decided that it's strong enough for this purpose and it's much easier to get everyone to use it.
Don't know if this is necessary

2023-01-27 05:41 UTC, ThorodanBrom commented on CONTRIBUTING.md
> +-   [vulnerability reporting](https://github.com/coreinfrastructure/best-practices-badge/blob/main/CONTRIBUTING.md#how_to_report_vulnerabilities),
Update URL here

2023-02-02 04:22 UTC, abhi4578 requested changes

2023-02-02 04:22 UTC, abhi4578 commented on CONTRIBUTING.md
> +  fix problems.
We can mention JaCoCo code coverage tool, postman and newman.

2023-02-02 04:22 UTC, abhi4578 commented on CONTRIBUTING.md
> +
Add this section
### Testing during continuous integration

Note that we also use
[Jenkins](https://jenkins.iudx.io/)
for continuous integration tools to check changes
after they are checked into GitHub; if they find problems, please fix them.
These run essentially the Junit tests, JaCoCo code coverage tests, security tests using OWASP ZAP and integration tests using postman and newman

2023-02-12 18:46 UTC, abhi4578 commented
retest this please

2023-02-13 04:03 UTC, abhi4578 approved these changes

2023-02-13 04:04 UTC, merged